/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logins;
import java.sql.*;
import Project.Connectionprovider;
import javax.swing.JOptionPane;


/**
 *
 * @author Akib
 */
public class DeleteDrugDetails extends javax.swing.JFrame {

    /**
     * Creates new form DeleteDrugDetails
     */
    public DeleteDrugDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        DeleteButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jTextField11 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/delete product.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/delete product ani.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 126, 570, 10));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("DrugID :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 149, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Drug Name :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 185, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Scientific Name :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 223, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Company Name :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 261, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("InStock");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 292, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Description :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 321, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Issue Date :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 359, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Expire Date :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 397, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Price :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 435, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText(" Row :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 185, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Column :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 223, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 146, 130, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 182, 130, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 220, 130, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 258, 130, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 289, 130, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 318, 350, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 356, 130, -1));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 394, 133, -1));

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 432, 133, -1));

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 182, 85, -1));

        DeleteButton.setBackground(new java.awt.Color(153, 153, 153));
        DeleteButton.setFont(new java.awt.Font("Tahoma", 3, 9)); // NOI18N
        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/delete.png"))); // NOI18N
        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 470, -1, -1));

        ResetButton.setBackground(new java.awt.Color(153, 153, 153));
        ResetButton.setFont(new java.awt.Font("Tahoma", 3, 9)); // NOI18N
        ResetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/Reset.png"))); // NOI18N
        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ResetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 470, -1, -1));

        Exit.setBackground(new java.awt.Color(153, 153, 153));
        Exit.setFont(new java.awt.Font("Tahoma", 3, 9)); // NOI18N
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/close Jframe.png"))); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, -1, -1));

        SearchButton.setBackground(new java.awt.Color(0, 153, 255));
        SearchButton.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        SearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/search.png"))); // NOI18N
        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 142, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Main Store", "Branch A", "Branch B" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 110, -1));

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 223, 85, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/pill-tablet-pharmacy-medicine.jpg"))); // NOI18N
        jLabel14.setPreferredSize(new java.awt.Dimension(580, 499));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
         String DrugID=jTextField1.getText();
         try
        {
            Connection con= Connectionprovider.getcon();
            int selected =  jComboBox1.getSelectedIndex();
            if(selected == 0){
                 Statement st=con.createStatement();
                 ResultSet rs=st.executeQuery("select *from store where DrugID ='"+DrugID+"'");
                 if (rs.next()){
                      jTextField2.setText(rs.getString(2));
                      jTextField3.setText(rs.getString(3));
                      jTextField4.setText(rs.getString(4));
                      jTextField5.setText(rs.getString(5));
                      jTextField6.setText(rs.getString(6));
                      jTextField7.setText(rs.getString(7));
                      jTextField8.setText(rs.getString(8));
                      jTextField9.setText(rs.getString(9));
                      jTextField10.setText(rs.getString(10));
                      jTextField11.setText(rs.getString(11));
                     
                
                 }
                 else{
                     JOptionPane.showMessageDialog(null, "Drug ID doesn't exist!");
                 }
            }
            if(selected == 1){
                 Statement st2=con.createStatement();
                 ResultSet rs2=st2.executeQuery("select *from brancha where DrugID ='"+DrugID+"'");
                 if (rs2.next()){
                      jTextField2.setText(rs2.getString(2));
                      jTextField3.setText(rs2.getString(3));
                      jTextField4.setText(rs2.getString(4));
                      jTextField5.setText(rs2.getString(5));
                      jTextField6.setText(rs2.getString(6));
                      jTextField7.setText(rs2.getString(7));
                      jTextField8.setText(rs2.getString(8));
                      jTextField9.setText(rs2.getString(9));
                      jTextField10.setText(rs2.getString(10));
                      jTextField11.setText(rs2.getString(11));
                      
                
                 }
                 else{
                     JOptionPane.showMessageDialog(null, "Drug ID doesn't exist!");
                 }
            }
            if(selected == 2){
                 Statement st3=con.createStatement();
                 ResultSet rs3=st3.executeQuery("select *from branchb where DrugID ='"+DrugID+"'");
                 if (rs3.next()){
                      jTextField2.setText(rs3.getString(2));
                      jTextField3.setText(rs3.getString(3));
                      jTextField4.setText(rs3.getString(4));
                      jTextField5.setText(rs3.getString(5));
                      jTextField6.setText(rs3.getString(6));
                      jTextField7.setText(rs3.getString(7));
                      jTextField8.setText(rs3.getString(8));
                      jTextField9.setText(rs3.getString(9));
                      jTextField10.setText(rs3.getString(10));
                      jTextField11.setText(rs3.getString(11));
                      
                
                 }
                 else{
                     JOptionPane.showMessageDialog(null, "Drug ID doesn't exist!");
                 }
            }
            
            
        }
         catch (Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
       String DrugId=jTextField1.getText();
        try{
            Connection con= Connectionprovider.getcon();
            int selected =  jComboBox1.getSelectedIndex();
            if(selected == 0){
                Statement st=con.createStatement();
                st.executeUpdate("delete from store where DrugId ='"+DrugId+"'");
                
            }
            if(selected == 1){
                Statement st2=con.createStatement();
                st2.executeUpdate("delete from brancha where DrugId ='"+DrugId+"'");
                
            }
            if(selected == 2){
                Statement st3=con.createStatement();
                st3.executeUpdate("delete from branchb where DrugId ='"+DrugId+"'");
                
            }
            JOptionPane.showMessageDialog(null,"Successfully Deleted");
            setVisible(false);
            new DeleteDrugDetails().setVisible(true);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        setVisible(false);
        new DeleteDrugDetails().setVisible(true);
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        setVisible(false);
        new MainStore().setVisible(true);
        dispose();
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteDrugDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteDrugDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteDrugDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteDrugDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteDrugDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton Exit;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
