/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logins;
import java.sql.*;
import javax.swing.*;
import Project.Connectionprovider;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import logins.NewDrug;
import logins.UpdateDrugDetails;
import logins.DeleteDrugDetails;
import logins.ShiftProduct;
import java.text.SimpleDateFormat;
import java.util.Date;
import logins.adminProfile;

/**
 *
 * @author Akib
 */
public class MainStore extends javax.swing.JFrame {

    /**
     * Creates new form MainStore
     */
    public MainStore() {
        initComponents();
         showTime();
        SimpleDateFormat SDFormat= new SimpleDateFormat("dd-MM-yyyy");
        Date dt=new Date();
        Date.setText(SDFormat.format(dt));
       
    }
   
      void showTime(){
        
         new Timer(0, new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                 SimpleDateFormat SDFormat= new SimpleDateFormat("hh:mm:ss a");
                 Date dt=new Date();
                 Time.setText(SDFormat.format(dt));
            }
        }
        
        
        ).start();
        
    }    
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlevele00 = new javax.swing.JLabel();
        Tlebel = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Drugid = new javax.swing.JTextField();
        Drugname = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        NewDrugButton = new javax.swing.JButton();
        UpdateDrugButton = new javax.swing.JButton();
        DeleteDrugButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ShiftDrugButton = new javax.swing.JButton();
        AdminProfileButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/rsz_1rsz_1rsz_15c9898a4eea31_thumb900.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sylfaen", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 0));
        jLabel3.setText("Mediline Pharmacy (Store)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 230, 23));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 9)); // NOI18N
        jLabel4.setText("Always there to care.!!");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 120, 20));

        jlevele00.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlevele00.setText("Date :");
        getContentPane().add(jlevele00, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        Tlebel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Tlebel.setText("Time :");
        getContentPane().add(Tlebel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        Date.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 70, -1));

        Time.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, 10));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Drug ID :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Drug Name:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 142, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Scientific Name :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 183, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Company Name:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 217, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("InStock :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 247, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Description:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 288, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Issue Date :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 317, -1, -1));

        Drugid.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Drugid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrugidActionPerformed(evt);
            }
        });
        Drugid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DrugidKeyPressed(evt);
            }
        });
        getContentPane().add(Drugid, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 98, -1));

        Drugname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Drugname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrugnameActionPerformed(evt);
            }
        });
        getContentPane().add(Drugname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 98, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 98, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 98, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 98, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 220, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 98, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Expire Date:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 355, -1, -1));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 98, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Price :");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 381, -1, -1));

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 98, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Row :");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Store", "Branch A", "Branch B" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Column :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 67, -1));

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 64, -1));

        NewDrugButton.setBackground(new java.awt.Color(0, 153, 255));
        NewDrugButton.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        NewDrugButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/add.png"))); // NOI18N
        NewDrugButton.setText("New Drug");
        NewDrugButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewDrugButtonActionPerformed(evt);
            }
        });
        getContentPane().add(NewDrugButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 120, -1));

        UpdateDrugButton.setBackground(new java.awt.Color(0, 153, 255));
        UpdateDrugButton.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        UpdateDrugButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/rsz_1rsz_1rsz_1rsz_2rsz_1rsz_1rsz_1images_6.jpg"))); // NOI18N
        UpdateDrugButton.setText("Update Drug");
        UpdateDrugButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDrugButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateDrugButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 120, 30));

        DeleteDrugButton.setBackground(new java.awt.Color(0, 153, 255));
        DeleteDrugButton.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        DeleteDrugButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/delete.png"))); // NOI18N
        DeleteDrugButton.setText("Delete Drug");
        DeleteDrugButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteDrugButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteDrugButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 120, 30));

        ResetButton.setBackground(new java.awt.Color(153, 153, 153));
        ResetButton.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        ResetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/Reset.png"))); // NOI18N
        ResetButton.setText("Reset");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ResetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 91, -1));

        ExitButton.setBackground(new java.awt.Color(153, 153, 153));
        ExitButton.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/close Jframe.png"))); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 94, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 89, 562, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 427, 553, 10));

        ShiftDrugButton.setBackground(new java.awt.Color(0, 153, 255));
        ShiftDrugButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ShiftDrugButton.setText("Shift Drug");
        ShiftDrugButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShiftDrugButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ShiftDrugButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 373, 120, 30));

        AdminProfileButton.setBackground(new java.awt.Color(0, 102, 255));
        AdminProfileButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AdminProfileButton.setText("AdminProfile");
        AdminProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminProfileButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AdminProfileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/photo-1587370560942-ad2a04eabb6d.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(601, 501));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -9, 600, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DrugnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrugnameActionPerformed
         String DrugNAME=Drugname.getText();
         try
        {
            Connection con= Connectionprovider.getcon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from store where DrugName ='"+DrugNAME+"'");
            if (rs.next()){
                 Drugid.setText(rs.getString(1));
                  jTextField3.setText(rs.getString(3));
                   jTextField4.setText(rs.getString(4));
                   jTextField5.setText(rs.getString(5));
                  jTextField6.setText(rs.getString(6));
                   jTextField7.setText(rs.getString(7));
                   jTextField8.setText(rs.getString(8));
                  jTextField9.setText(rs.getString(9));
                   jTextField10.setText(rs.getString(10));
                   jTextField11.setText(rs.getString(11));
                   
                    
            }
                
            else{
                   Drugid.setText("");
                  jTextField3.setText("");
                   jTextField4.setText("");
                   jTextField5.setText("");
                  jTextField6.setText("");
                   jTextField7.setText("");
                   jTextField8.setText("");
                  jTextField9.setText("");
                   jTextField10.setText("");
                   jTextField11.setText("");
            }
            }
         catch (Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
    }//GEN-LAST:event_DrugnameActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void DrugidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrugidActionPerformed
        String DrugID=Drugid.getText();
         try
        {   
            int selected =  jComboBox1.getSelectedIndex();
           
            if(selected == 0){
                 Connection con= Connectionprovider.getcon();
                 Statement st=con.createStatement();
                 ResultSet rs1=st.executeQuery("select *from store where DrugId ='"+DrugID+"'");
                 if (rs1.next()){
                    Drugname.setText(rs1.getString(2));
                    jTextField3.setText(rs1.getString(3));
                    jTextField4.setText(rs1.getString(4));
                    jTextField5.setText(rs1.getString(5));
                    jTextField6.setText(rs1.getString(6));
                    jTextField7.setText(rs1.getString(7));
                    jTextField8.setText(rs1.getString(8));
                    jTextField9.setText(rs1.getString(9));
                    jTextField10.setText(rs1.getString(10));
                    jTextField11.setText(rs1.getString(11));
                   
                 }      
            
             }   
            else if(selected == 1){
                  Connection con= Connectionprovider.getcon();
                  Statement st=con.createStatement();
                  ResultSet rs2=st.executeQuery("select *from brancha where DrugId ='"+DrugID+"'");
                  if (rs2.next()){
                    Drugname.setText(rs2.getString(2));
                    jTextField3.setText(rs2.getString(3));
                    jTextField4.setText(rs2.getString(4));
                    jTextField5.setText(rs2.getString(5));
                    jTextField6.setText(rs2.getString(6));
                    jTextField7.setText(rs2.getString(7));
                    jTextField8.setText(rs2.getString(8));
                    jTextField9.setText(rs2.getString(9));
                    jTextField10.setText(rs2.getString(10));
                    jTextField11.setText(rs2.getString(11));
                   
                 }  
            }
            else if(selected == 2){
                  Connection con= Connectionprovider.getcon();
                  Statement st=con.createStatement();
                  ResultSet rs3=st.executeQuery("select *from branchb where DrugId ='"+DrugID+"'");
                  if (rs3.next()){
                    Drugname.setText(rs3.getString(2));
                    jTextField3.setText(rs3.getString(3));
                    jTextField4.setText(rs3.getString(4));
                    jTextField5.setText(rs3.getString(5));
                    jTextField6.setText(rs3.getString(6));
                    jTextField7.setText(rs3.getString(7));
                    jTextField8.setText(rs3.getString(8));
                    jTextField9.setText(rs3.getString(9));
                    jTextField10.setText(rs3.getString(10));
                    jTextField11.setText(rs3.getString(11));
                   
                 }  
            }
            else{
                   Drugname.setText("");
                  jTextField3.setText("");
                   jTextField4.setText("");
                   jTextField5.setText("");
                  jTextField6.setText("");
                   jTextField7.setText("");
                   jTextField8.setText("");
                  jTextField9.setText("");
                   jTextField10.setText("");
                   jTextField11.setText("");
            }
            
            }
         catch (Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
    }//GEN-LAST:event_DrugidActionPerformed

    private void NewDrugButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewDrugButtonActionPerformed
        NewDrug nd= new NewDrug();
        nd.setVisible(true);
    }//GEN-LAST:event_NewDrugButtonActionPerformed

    private void UpdateDrugButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDrugButtonActionPerformed
       UpdateDrugDetails UPD= new UpdateDrugDetails();
        UPD.setVisible(true);
    }//GEN-LAST:event_UpdateDrugButtonActionPerformed

    private void DeleteDrugButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteDrugButtonActionPerformed
        DeleteDrugDetails DPD= new DeleteDrugDetails();
        DPD.setVisible(true);
    }//GEN-LAST:event_DeleteDrugButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        setVisible(false);
        new MainStore().setVisible(true);
    }//GEN-LAST:event_ResetButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        setVisible(false);
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void DrugidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DrugidKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DrugidKeyPressed

    private void ShiftDrugButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShiftDrugButtonActionPerformed
        ShiftProduct sp = new ShiftProduct();
        sp.setVisible(true);
    }//GEN-LAST:event_ShiftDrugButtonActionPerformed

    private void AdminProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminProfileButtonActionPerformed
        adminProfile ap=new adminProfile();
        ap.setVisible(true);
    }//GEN-LAST:event_AdminProfileButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainStore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminProfileButton;
    private javax.swing.JLabel Date;
    private javax.swing.JButton DeleteDrugButton;
    private javax.swing.JTextField Drugid;
    private javax.swing.JTextField Drugname;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton NewDrugButton;
    private javax.swing.JButton ResetButton;
    private javax.swing.JButton ShiftDrugButton;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel Tlebel;
    private javax.swing.JButton UpdateDrugButton;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel jlevele00;
    // End of variables declaration//GEN-END:variables
}
