/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package logins;
import java.sql.*;
import javax.swing.*;
import Project.Connectionprovider;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import logins.Order;




/**
 *
 * @author Akib
 */
public final class PharmacyM extends javax.swing.JFrame {
public String TotalAmount;
public int returnAmount;
    /**
     * Creates new form PharmacyM
     */
    public PharmacyM() {
        initComponents();
        showTime();
        SimpleDateFormat SDFormat= new SimpleDateFormat("dd-MM-yyyy");
        Date dt=new Date();
        Date.setText(SDFormat.format(dt));
       
    }
    void showTime(){
        
         new Timer(0, new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                 SimpleDateFormat SDFormat= new SimpleDateFormat("hh.mm.ss a");
                 Date dt=new Date();
                 Time.setText(SDFormat.format(dt));
            }
        }
        
        
        ).start();
        
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        PaidAmount = new javax.swing.JTextField();
        ReturnAmount = new javax.swing.JTextField();
        Save = new javax.swing.JButton();
        Resetbutton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        des = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        idate = new javax.swing.JTextField();
        edate = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        row = new javax.swing.JTextField();
        col = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        quan = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/pill-tablet-pharmacy-medicine.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 153, 0));
        jLabel1.setText("Mediline Pharmacy");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 230, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/rsz_1rsz_1rsz_15c9898a4eea31_thumb900.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 20, 80, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Date :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, 20));

        Date.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 80, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Time :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 64, -1, 20));

        Time.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 70, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 115, 657, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Drug ID       :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 138, 90, -1));

        id.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 150, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Drug Name :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 169, 90, -1));

        name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 150, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Scientific Name:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        sname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 150, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Company Name:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 110, -1));

        cname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });
        getContentPane().add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 150, -1));

        Add.setBackground(new java.awt.Color(51, 102, 255));
        Add.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/add.png"))); // NOI18N
        Add.setText("ADD");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 264, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Id", "Name", "Rate", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 340, 180));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Calculation Details :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, 25));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Total Amount   :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Paid Amount     :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Return Amount :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, -1, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 150, -1));

        PaidAmount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PaidAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaidAmountActionPerformed(evt);
            }
        });
        getContentPane().add(PaidAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 150, -1));

        ReturnAmount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(ReturnAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 150, -1));

        Save.setBackground(new java.awt.Color(0, 153, 255));
        Save.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/save.png"))); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, -1, -1));

        Resetbutton.setBackground(new java.awt.Color(204, 204, 255));
        Resetbutton.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        Resetbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/Reset.png"))); // NOI18N
        Resetbutton.setText("Reset");
        Resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Resetbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, -1, -1));

        ExitButton.setBackground(new java.awt.Color(204, 204, 255));
        ExitButton.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/close Jframe.png"))); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, 80, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI Symbol", 3, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Always there to care.!!");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 160, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Description :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 70, 20));

        stock.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 150, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("InStock :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 90, 20));

        des.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(des, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 480, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Issue Date :");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 70, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Exp Date :");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 60, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Price :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 60, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Row :");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 60, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Column :");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 70, -1));

        idate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(idate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 140, -1));

        edate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        edate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edateActionPerformed(evt);
            }
        });
        getContentPane().add(edate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 140, -1));

        price.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 140, -1));

        row.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(row, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 140, -1));

        col.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(col, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 140, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Quantity :");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 90, -1));

        quan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(quan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 150, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 419, 259, 10));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 100, 30));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/photo-1587370560942-ad2a04eabb6d.jpg"))); // NOI18N
        jLabel23.setPreferredSize(new java.awt.Dimension(657, 580));
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PaidAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaidAmountActionPerformed
        String Paidamount=PaidAmount.getText();
        int givenAmount=Integer.parseInt(Paidamount);
    
        String cost = jTextField5.getText();
        int drugCost = Integer.parseInt(cost);
        returnAmount = givenAmount - drugCost;
        String returnamount=String.valueOf(returnAmount);
         ReturnAmount.setText(returnamount);
         ReturnAmount.setEditable(false);
        
    }//GEN-LAST:event_PaidAmountActionPerformed

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
       
        setVisible(false);
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ResetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetbuttonActionPerformed
        setVisible (false);
        new PharmacyM().setVisible(true);
        
    }//GEN-LAST:event_ResetbuttonActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        String DrugId=id.getText();
         try
        {
            Connection con= Connectionprovider.getcon();
                 Statement st=con.createStatement();
                 ResultSet rs1=st.executeQuery("select *from brancha where DrugId ='"+DrugId+"'");
                 if (rs1.next()){
                    name.setText(rs1.getString(2));
                    sname.setText(rs1.getString(3));
                    cname.setText(rs1.getString(4));
                    stock.setText(rs1.getString(5));
                    des.setText(rs1.getString(6));
                    idate.setText(rs1.getString(7));
                    edate.setText(rs1.getString(8));
                    price.setText(rs1.getString(9));
                    row.setText(rs1.getString(10));
                    col.setText(rs1.getString(11));
                  
                 }
                
            else{
                    name.setText("");
                    sname.setText("");
                    cname.setText("");
                    stock.setText("");
                    des.setText("");
                    idate.setText("");
                    edate.setText("");
                    price.setText("");
                    row.setText("");
                    col.setText("");
            }
            }
         catch (Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
    }//GEN-LAST:event_idActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
       String DrugName=name.getText();
         try
        {
            Connection con= Connectionprovider.getcon();
                 Statement st=con.createStatement();
                 ResultSet rs1=st.executeQuery("select *from brancha where DrugName ='"+DrugName+"'");
                 if (rs1.next()){
                    id.setText(rs1.getString(1));
                    sname.setText(rs1.getString(3));
                    cname.setText(rs1.getString(4));
                    stock.setText(rs1.getString(5));
                    des.setText(rs1.getString(6));
                    idate.setText(rs1.getString(7));
                    edate.setText(rs1.getString(8));
                    price.setText(rs1.getString(9));
                    row.setText(rs1.getString(10));
                    col.setText(rs1.getString(11));
                  
                 }
                
            else{
                    id.setText("");
                    sname.setText("");
                    cname.setText("");
                    stock.setText("");
                    des.setText("");
                    idate.setText("");
                    edate.setText("");
                    price.setText("");
                    row.setText("");
                    col.setText("");
            }
            }
         catch (Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
    }//GEN-LAST:event_nameActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        int sum=0;
        int Price=Integer.parseInt(price.getText());
        int quantity=Integer.parseInt(quan.getText());
        int total= Price*quantity;
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[]{id.getText(), name.getText(),Price,quantity,total});
        for(int i=0;i<jTable1.getRowCount();i++){
            
           
           sum=sum+Integer.parseInt(jTable1.getValueAt(i,4).toString());
        }  
        
        String Totalamount=String.valueOf(sum);
        jTextField5.setText(Totalamount);
        
        String drugID=id.getText();
         String drugName=name.getText();
         String scientificName=sname.getText();
         String companyName=cname.getText();
         int instock = Integer.parseInt(stock.getText()) - quantity;
         String currInstock = String.valueOf(instock);
         String description=des.getText();
         String issueDate=idate.getText();
         String expireDate=edate.getText();
         String rate=price.getText();
         String Row=row.getText();
         String Column=col.getText();
         
        try{
                
            Connection con= Connectionprovider.getcon();
            Statement st=con.createStatement();
            st.executeUpdate("delete from brancha where DrugId ='"+drugID+"'");
            st.executeUpdate("Insert into brancha value('"+drugID+"','"+drugName+"','"+scientificName+"','"+companyName+"','"+currInstock+"','"+description+"','"+issueDate+"','"+expireDate+"','"+rate+"','"+Row+"','"+Column+"')");
            
        } catch (Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
                
    }//GEN-LAST:event_AddActionPerformed

    private void edateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edateActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
 Document doc = new Document();
      
    try {
        String purchasedDate = Date.getText();
        String purchasedTime = Time.getText();
        
        PdfWriter.getInstance(doc, new FileOutputStream(purchasedDate+"_"+purchasedTime+".pdf"));
        doc.open();
        
        doc.add(new Paragraph("                                                                 Mediline Pharma\n\n      "));
        
         doc.add(new Paragraph("Purchased date:"+purchasedDate+"                                    "+"purchased time:"+purchasedTime+"\n\n\n"));
        
        PdfPTable tb1 = new PdfPTable(5);
        tb1.addCell("Drug Id");
        tb1.addCell("Name");
        tb1.addCell("Rate");
        tb1.addCell("Quantity");
        tb1.addCell("Total");
        
        for(int i=0;i<jTable1.getRowCount();i++)
        {
            String id = jTable1.getValueAt(i,0).toString();
            String name = jTable1.getValueAt(i,1).toString();
            String rate = jTable1.getValueAt(i,2).toString();
            String quantity = jTable1.getValueAt(i,3).toString();
            String total = jTable1.getValueAt(i,4).toString();
            
            tb1.addCell(id);
            tb1.addCell(name);
            tb1.addCell(rate);
            tb1.addCell(quantity);
            tb1.addCell(total);
            
        }
        
        doc.add(tb1);
        String totalAmount = jTextField5.getText();
        String paid = PaidAmount.getText();
        String returnAmount = ReturnAmount.getText();
        
        
        doc.add(new Paragraph("\n"+"Total Cost :" + totalAmount+"\nPaid Amount :"+ paid+"\nReturned Amount :"+ returnAmount));
       
        JOptionPane.showMessageDialog(null, "Successfully Saved");
        
    } catch (FileNotFoundException ex) {
        Logger.getLogger(PharmacyM.class.getName()).log(Level.SEVERE, null, ex);
    } catch (DocumentException ex) {
        Logger.getLogger(PharmacyM.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    doc.close();        
        
    }//GEN-LAST:event_SaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Order or= new Order();
        or.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PharmacyM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PharmacyM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PharmacyM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PharmacyM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PharmacyM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JLabel Date;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField PaidAmount;
    private javax.swing.JButton Resetbutton;
    private javax.swing.JTextField ReturnAmount;
    private javax.swing.JButton Save;
    private javax.swing.JLabel Time;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField col;
    private javax.swing.JTextField des;
    private javax.swing.JTextField edate;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quan;
    private javax.swing.JTextField row;
    private javax.swing.JTextField sname;
    private javax.swing.JTextField stock;
    // End of variables declaration//GEN-END:variables
}
