/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logins;

import Project.Connectionprovider;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author MN
 */
public class ShiftProduct extends javax.swing.JFrame {

    /**
     * Creates new form ShiftProduct
     */
    public ShiftProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        cname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        row = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        column = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        inStockM = new javax.swing.JTextField();
        inStockA = new javax.swing.JTextField();
        inStockB = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jLabel16 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        ShiftButton = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Drug ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 23, 112, 34));

        id.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 23, 124, 34));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Drug Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 112, 34));

        name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 80, 124, 34));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Scientific Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 132, 112, 34));

        sname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(sname, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 132, 124, 34));

        cname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 184, 124, 34));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Company Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 184, 112, 34));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Issue Date:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 242, 112, 34));

        idate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(idate, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 242, 124, 34));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Expire Date:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 112, 34));

        edate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(edate, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 300, 124, 34));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Price:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 357, 112, 34));

        price.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 357, 124, 34));

        description.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 414, 244, 34));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Description:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 414, 112, 34));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Row:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 23, 73, 34));

        row.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(row, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 23, 124, 34));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Column:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 80, 73, 34));

        column.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(column, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 80, 124, 34));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("InStock:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 242, 68, 35));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setText("MAIN STORE");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 192, -1, 35));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setText("BRANCH A");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 192, -1, 35));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel14.setText("BRANCH B");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 192, -1, 35));

        inStockM.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        inStockM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inStockMActionPerformed(evt);
            }
        });
        getContentPane().add(inStockM, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 50, 35));

        inStockA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(inStockA, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 242, 50, 35));

        inStockB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        inStockB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inStockBActionPerformed(evt);
            }
        });
        getContentPane().add(inStockB, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 242, 50, 35));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("BRANCH:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 491, 90, 49));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "       A", "       B" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 491, 73, 49));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("QUANITY:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 493, 68, 44));

        quantity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 493, 77, 44));

        ShiftButton.setBackground(new java.awt.Color(0, 153, 255));
        ShiftButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ShiftButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/add.png"))); // NOI18N
        ShiftButton.setText("SHIFT");
        ShiftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShiftButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ShiftButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 90, 40));

        reset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/Reset.png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 98, 30));

        exit.setBackground(new java.awt.Color(153, 153, 153));
        exit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/close Jframe.png"))); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 600, 92, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/photo-1587370560942-ad2a04eabb6d.jpg"))); // NOI18N
        jLabel17.setPreferredSize(new java.awt.Dimension(626, 669));
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -11, 670, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inStockBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inStockBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inStockBActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        String DrugID=id.getText();
         try
        {   
            
           
            
                 Connection con= Connectionprovider.getcon();
                 Statement st=con.createStatement();
                 ResultSet rs1=st.executeQuery("select *from store where DrugId ='"+DrugID+"'");
                 if (rs1.next()){
                    name.setText(rs1.getString(2));
                    sname.setText(rs1.getString(3));
                    cname.setText(rs1.getString(4));
                    inStockM.setText(rs1.getString(5));
                    description.setText(rs1.getString(6));
                    idate.setText(rs1.getString(7));
                    edate.setText(rs1.getString(8));
                    price.setText(rs1.getString(9));
                    row.setText(rs1.getString(10));
                    column.setText(rs1.getString(11));
                    inStockA.setText("0");
                    inStockB.setText("0");
                  
                 }   
                 
              
                 Statement st2=con.createStatement();
                ResultSet rs2=st2.executeQuery("select *from brancha where DrugId ='"+DrugID+"'");
                if(rs2.next())
                 {
                      inStockA.setText(rs2.getString(5));
                    
                 }
                 
              
                Statement st3=con.createStatement();
                 ResultSet rs3=st3.executeQuery("select *from branchb where DrugId ='"+DrugID+"'");
                if(rs3.next())
                {
                      inStockB.setText(rs3.getString(5));
                   
                }
                 
      
            
            }
         catch (Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
    }//GEN-LAST:event_idActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        setVisible(false);
        new ShiftProduct().setVisible(true);
    }//GEN-LAST:event_resetActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        setVisible(false);
        new MainStore().setVisible(true);
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void ShiftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShiftButtonActionPerformed
        String Id = id.getText();
        String Name = name.getText();
        String Cname = cname.getText();
        String Sname = sname.getText();
        String Idate = idate.getText();
        String Edate = edate.getText();
        String Price = price.getText();
        String Des = description.getText();
        String Row = row.getText();
        String Column = column.getText();
        String InM = inStockM.getText();
        String InA = inStockA.getText();
        String InB = inStockB.getText();
        String Quantity = quantity.getText();
        int shiftM = Integer.parseInt(InM) - Integer.parseInt(Quantity);
        int shiftA = Integer.parseInt(InA) + Integer.parseInt(Quantity);
        int shiftB = Integer.parseInt(InB) + Integer.parseInt(Quantity);
        String mainS = String.valueOf(shiftM);
        String branchA = String.valueOf(shiftA);
        String branchB = String.valueOf(shiftB);
        try{
             int selected =  jComboBox1.getSelectedIndex();
             Connection con= Connectionprovider.getcon();
             Statement st=con.createStatement();
             st.executeUpdate("delete from store where DrugId ='"+Id+"'");
             st.executeUpdate("Insert into store value('"+Id+"','"+Name+"','"+Cname+"','"+Sname+"','"+mainS+"','"+Des+"','"+Idate+"','"+Edate+"','"+Price+"','"+Row+"','"+Column+"')"); 
             
             if(selected == 0)
             {
                 Statement st2=con.createStatement();
                 ResultSet rs2=st2.executeQuery("select *from brancha where DrugId ='"+Id+"'");
                 if (rs2.next()){
                     st.executeUpdate("delete from brancha where DrugId ='"+Id+"'");
                 }
                 st.executeUpdate("Insert into brancha value('"+Id+"','"+Name+"','"+Cname+"','"+Sname+"','"+branchA+"','"+Des+"','"+Idate+"','"+Edate+"','"+Price+"','"+Row+"','"+Column+"')"); 
                 
                 JOptionPane.showMessageDialog(null,"Successfully Shifted To Branch A");
                 setVisible(false);
                 new ShiftProduct().setVisible(true);
             }
        
             if(selected == 1)
             {
                 Statement st3=con.createStatement();
                 ResultSet rs3=st3.executeQuery("select *from branchb where DrugId ='"+Id+"'");
                 if (rs3.next()){
                     st.executeUpdate("delete from branchb where DrugId ='"+Id+"'");
                 }
                 st.executeUpdate("Insert into branchb value('"+Id+"','"+Name+"','"+Cname+"','"+Sname+"','"+branchB+"','"+Des+"','"+Idate+"','"+Edate+"','"+Price+"','"+Row+"','"+Column+"')"); 
             
                 JOptionPane.showMessageDialog(null,"Successfully Shifted To Branch B");
                 setVisible(false);
                 new ShiftProduct().setVisible(true);
             }
             
             
        }catch (Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
       
    }//GEN-LAST:event_ShiftButtonActionPerformed

    private void inStockMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inStockMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inStockMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShiftProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShiftProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShiftProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShiftProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShiftProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ShiftButton;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField column;
    private javax.swing.JTextField description;
    private javax.swing.JTextField edate;
    private javax.swing.JButton exit;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idate;
    private javax.swing.JTextField inStockA;
    private javax.swing.JTextField inStockB;
    private javax.swing.JTextField inStockM;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JTextField price;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton reset;
    private javax.swing.JTextField row;
    private javax.swing.JTextField sname;
    // End of variables declaration//GEN-END:variables
}
