/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logins;

import java.awt.Color;
import java.sql.*;
import Project.Connectionprovider;
import java.awt.event.ActionEvent ;
import javax.swing.JOptionPane;

/**
 *
 * @author Akib
 */
public class UpdateDrugDetails extends javax.swing.JFrame {

    /**
     * Creates new form UpdateDrugDetails
     */
    public UpdateDrugDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();

        jLabel14.setText("jLabel14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/update product.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/update product ani.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Drud ID :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 93, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Drug Name :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 106, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Scientific Name :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 106, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Company Name :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 106, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("InStock :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 272, 106, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Description");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 310, 106, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Issue Date :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 345, 106, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Expire Date :\n");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 372, 96, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Price :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 402, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Row :\n");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Column :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 99, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 99, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 99, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 99, -1));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 269, 99, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 307, 240, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 339, 99, -1));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 369, 99, -1));

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 399, 99, -1));

        SearchButton.setBackground(new java.awt.Color(0, 153, 255));
        SearchButton.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        SearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/search.png"))); // NOI18N
        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 90, -1));

        SaveButton.setBackground(new java.awt.Color(153, 153, 153));
        SaveButton.setFont(new java.awt.Font("Tahoma", 3, 9)); // NOI18N
        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/save.png"))); // NOI18N
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 446, -1, -1));

        resetButton.setBackground(new java.awt.Color(153, 153, 153));
        resetButton.setFont(new java.awt.Font("Tahoma", 3, 9)); // NOI18N
        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/Reset.png"))); // NOI18N
        resetButton.setText("Reset\n");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 446, -1, -1));

        exitButton.setBackground(new java.awt.Color(153, 153, 153));
        exitButton.setFont(new java.awt.Font("Tahoma", 3, 9)); // NOI18N
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/close Jframe.png"))); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 446, 80, -1));

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 80, -1));

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 80, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 86, 405, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Main Store", "Branch A", "Branch B" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 110, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 134, 405, 10));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logins/pill-tablet-pharmacy-medicine.jpg"))); // NOI18N
        jLabel15.setPreferredSize(new java.awt.Dimension(495, 480));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
         String DrugID=jTextField1.getText();
         try
        {
            Connection con= Connectionprovider.getcon();
            int selected =  jComboBox1.getSelectedIndex();
            if(selected == 0){
                 Statement st=con.createStatement();
                 ResultSet rs=st.executeQuery("select *from store where DrugID ='"+DrugID+"'");
                 if (rs.next()){
                      jTextField2.setText(rs.getString(2));
                      jTextField3.setText(rs.getString(3));
                      jTextField4.setText(rs.getString(4));
                      jTextField5.setText(rs.getString(5));
                      jTextField6.setText(rs.getString(6));
                      jTextField7.setText(rs.getString(7));
                      jTextField8.setText(rs.getString(8));
                      jTextField9.setText(rs.getString(9));
                      jTextField10.setText(rs.getString(10));
                      jTextField11.setText(rs.getString(11));
                     
                
                 }
                 else{
                     JOptionPane.showMessageDialog(null, "Drug ID doesn't exist!");
                 }
            }
            if(selected == 1){
                 Statement st2=con.createStatement();
                 ResultSet rs2=st2.executeQuery("select *from brancha where DrugID ='"+DrugID+"'");
                 if (rs2.next()){
                      jTextField2.setText(rs2.getString(2));
                      jTextField3.setText(rs2.getString(3));
                      jTextField4.setText(rs2.getString(4));
                      jTextField5.setText(rs2.getString(5));
                      jTextField6.setText(rs2.getString(6));
                      jTextField7.setText(rs2.getString(7));
                      jTextField8.setText(rs2.getString(8));
                      jTextField9.setText(rs2.getString(9));
                      jTextField10.setText(rs2.getString(10));
                      jTextField11.setText(rs2.getString(11));
                      
                
                 }
                 else{
                     JOptionPane.showMessageDialog(null, "Drug ID doesn't exist!");
                 }
            }
            if(selected == 2){
                 Statement st3=con.createStatement();
                 ResultSet rs3=st3.executeQuery("select *from branchb where DrugID ='"+DrugID+"'");
                 if (rs3.next()){
                      jTextField2.setText(rs3.getString(2));
                      jTextField3.setText(rs3.getString(3));
                      jTextField4.setText(rs3.getString(4));
                      jTextField5.setText(rs3.getString(5));
                      jTextField6.setText(rs3.getString(6));
                      jTextField7.setText(rs3.getString(7));
                      jTextField8.setText(rs3.getString(8));
                      jTextField9.setText(rs3.getString(9));
                      jTextField10.setText(rs3.getString(10));
                      jTextField11.setText(rs3.getString(11));
                      
                
                 }
                 else{
                     JOptionPane.showMessageDialog(null, "Drug ID doesn't exist!");
                 }
            }
            
            
        }
         catch (Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
         String drugID=jTextField1.getText();
         String drugName=jTextField2.getText();
         String scientificName=jTextField3.getText();
         String companyName=jTextField4.getText();
         String inStock=jTextField5.getText();
         String description=jTextField6.getText();
         String issueDate=jTextField7.getText();
         String expireDate=jTextField8.getText();
         String price=jTextField9.getText();
         String row=jTextField10.getText();
         String column=jTextField11.getText();
        
        
      
        try{
            Connection con= Connectionprovider.getcon();
            int selected =  jComboBox1.getSelectedIndex();
            if(selected == 0){
                Statement st=con.createStatement();
                st.executeUpdate("delete from store where DrugId ='"+drugID+"'");
                st.executeUpdate("Insert into store value('"+drugID+"','"+drugName+"','"+scientificName+"','"+companyName+"','"+inStock+"','"+description+"','"+issueDate+"','"+expireDate+"','"+price+"','"+row+"','"+column+"')");
            }
            if(selected == 1){
                Statement st2=con.createStatement();
                st2.executeUpdate("delete from brancha where DrugId ='"+drugID+"'");
                st2.executeUpdate("Insert into brancha value('"+drugID+"','"+drugName+"','"+scientificName+"','"+companyName+"','"+inStock+"','"+description+"','"+issueDate+"','"+expireDate+"','"+price+"','"+row+"','"+column+"')");
            }
            if(selected == 2){
                Statement st3=con.createStatement();
                st3.executeUpdate("delete from branchb where DrugId ='"+drugID+"'");
                st3.executeUpdate("Insert into branchb value('"+drugID+"','"+drugName+"','"+scientificName+"','"+companyName+"','"+inStock+"','"+description+"','"+issueDate+"','"+expireDate+"','"+price+"','"+row+"','"+column+"')");
            }
            JOptionPane.showMessageDialog(null,"Successfully Updated");
            setVisible(false);
            new UpdateDrugDetails().setVisible(true);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        setVisible(false);
        new MainStore().setVisible(true);
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        setVisible(false);
        new UpdateDrugDetails().setVisible(true);        
    }//GEN-LAST:event_resetButtonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateDrugDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateDrugDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateDrugDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateDrugDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateDrugDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
}
