
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;
import Project.Connectionprovider;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Akib
 */
public class AdminProfile extends javax.swing.JFrame {

    /**
     * Creates new form AdminProfile
     */
    public AdminProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        old = new javax.swing.JTextField();
        New = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/119482056_3622741241094186_5048409055591734675_n.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 11, 110, 99));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("User Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 154, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Old Password :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 209, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("New Password :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 261, -1, -1));

        user.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 151, 189, -1));

        old.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(old, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 206, 189, -1));

        New.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(New, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 258, 189, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close Jframe.png"))); // NOI18N
        jButton2.setText("Exit");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 320, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reset.png"))); // NOI18N
        jButton3.setText("Reset");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String usernamee = user.getText();
         String password = old.getText();
         String newPass = New.getText();
        
        try{
            Connection con= Connectionprovider.getcon();
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select *from login where username ='"+usernamee+"'");
            
            if(rs.next()){
                if(usernamee.equals("admin") && password.equals(rs.getString(2)))
                {
                   st.executeUpdate("delete from login where username ='"+usernamee+"'");
                   st.executeUpdate("Insert into login value('"+usernamee+"','"+newPass+"')");
                   JOptionPane.showMessageDialog(null,"changed");
                   setVisible(false);
                }
                else if(usernamee.equals("branch") && password.equals(rs.getString(2)))
                {
                    st.executeUpdate("delete from login where username ='"+usernamee+"'");
                    st.executeUpdate("Insert into login value('"+usernamee+"','"+newPass+"')");
                    JOptionPane.showMessageDialog(null,"changed");
                    setVisible(false);
                }
                else
                {
                 JOptionPane.showMessageDialog(null,"Login Failed");
                 user.setText(null);
                 old.setText(null);
                 New.setText(null);
                 }
            }
       
            else
            {
               JOptionPane.showMessageDialog(null,"Login Failed");
               user.setText(null);
               old.setText(null);
               New.setText(null);
            }
        
        }catch (Exception e){
                JOptionPane.showMessageDialog(null,e);
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField New;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField old;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
